services:
  ai-search-lab:
    build: ./ai-search-lab
    ports:
      - "8888:8888"
    depends_on:
      - ai-search-opensearch-node
    volumes:
      - ai-search-lab-data:/home/jovyal/notebooks
    networks:
      - ai-search-network

  ai-search-opensearch-node:
    image: opensearchproject/opensearch:2.18.0
    container_name: ai-search-opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ai-search-opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - ai-search-network

  ai-search-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: ai-search-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://ai-search-opensearch-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - ai-search-opensearch-node   
    networks:
      - ai-search-network

volumes:
  ai-search-lab-data:
  ai-search-opensearch-data:

networks:
  ai-search-network:
    name: ai-search-network
